# Generated by Django 3.2.16 on 2023-01-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mosquito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=122)),
                ('mosquito', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='image',
        ),
    ]
