# Generated by Django 3.2.16 on 2023-01-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230127_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mosquito',
            old_name='date',
            new_name='created',
        ),
    ]
