# Generated by Django 3.2.16 on 2023-01-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_date_mosquito_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=122)),
                ('culex', models.IntegerField(default=0)),
                ('ades', models.IntegerField(default=0)),
                ('anoph', models.IntegerField(default=0)),
            ],
        ),
    ]
